-- Create the Chat Table
create table public.ride_chats (
  id bigint generated by default as identity primary key,
  ride_id bigint references public.rides(id) on delete cascade not null,
  user_address text not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Realtime (so messages appear instantly)
alter publication supabase_realtime add table ride_chats;

-- Enable RLS (Security)
alter table public.ride_chats enable row level security;

-- Allow anyone to read/write for this demo (or restrict to auth users)
create policy "Enable read for all" on public.ride_chats for select using (true);
create policy "Enable insert for all" on public.ride_chats for insert with check (true);
